name: Clojure CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.2
      with:
        # Install just one or all simultaneously
        cli:  latest     # Clojure CLI based on tools.deps
        boot: latest     # or use 'latest' to always provision latest version of boot

    - name: Run tests
      run: lein test
